// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        p_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [71:0] p_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;

wire   [7:0] trunc_ln1319_fu_1451_p1;
reg   [7:0] trunc_ln1319_reg_2903;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] trunc_ln1319_reg_2903_pp0_iter1_reg;
reg   [7:0] trunc_ln1319_reg_2903_pp0_iter2_reg;
reg   [7:0] trunc_ln864_s_reg_2914;
reg   [7:0] trunc_ln864_s_reg_2914_pp0_iter1_reg;
reg   [5:0] trunc_ln864_283_reg_2919;
reg   [7:0] tmp_112_reg_2924;
reg   [4:0] mult_V_reg_2932;
reg   [4:0] mult_V_reg_2932_pp0_iter1_reg;
reg  signed [7:0] a_V_1_reg_2937;
reg   [7:0] tmp_113_reg_2943;
reg   [6:0] mult_V_113_reg_2949;
reg   [6:0] mult_V_113_reg_2949_pp0_iter1_reg;
reg  signed [7:0] a_V_2_reg_2954;
reg   [7:0] tmp_114_reg_2959;
reg   [7:0] tmp_114_reg_2959_pp0_iter1_reg;
wire  signed [13:0] sext_ln70_2_fu_1635_p1;
reg   [9:0] trunc_ln864_295_reg_2976;
reg   [9:0] trunc_ln864_295_reg_2976_pp0_iter1_reg;
reg   [7:0] trunc_ln864_297_reg_2981;
reg   [4:0] mult_V_116_reg_2986;
reg   [4:0] mult_V_116_reg_2986_pp0_iter1_reg;
reg   [7:0] a_V_8_reg_2991;
reg   [7:0] a_V_8_reg_2991_pp0_iter1_reg;
wire   [7:0] tmp_116_fu_1749_p4;
reg   [7:0] tmp_116_reg_2996;
wire   [11:0] r_V_567_fu_1771_p2;
reg   [11:0] r_V_567_reg_3001;
reg   [10:0] trunc_ln864_301_reg_3006;
wire  signed [12:0] sext_ln70_3_fu_1841_p1;
reg   [8:0] trunc_ln864_302_reg_3017;
reg   [8:0] trunc_ln864_302_reg_3017_pp0_iter1_reg;
reg   [8:0] trunc_ln864_303_reg_3022;
reg   [7:0] trunc_ln864_307_reg_3032;
reg   [7:0] trunc_ln864_308_reg_3037;
reg   [7:0] trunc_ln864_308_reg_3037_pp0_iter1_reg;
reg   [7:0] trunc_ln864_308_reg_3037_pp0_iter2_reg;
wire   [9:0] add_ln859_642_fu_2016_p2;
reg   [9:0] add_ln859_642_reg_3042;
wire   [7:0] add_ln859_643_fu_2022_p2;
reg   [7:0] add_ln859_643_reg_3047;
wire   [5:0] add_ln859_648_fu_2028_p2;
reg   [5:0] add_ln859_648_reg_3052;
reg   [9:0] trunc_ln864_285_reg_3057;
reg   [9:0] trunc_ln864_286_reg_3062;
reg   [7:0] trunc_ln864_288_reg_3067;
reg   [9:0] trunc_ln864_290_reg_3072;
reg   [7:0] trunc_ln864_291_reg_3077;
reg   [7:0] trunc_ln864_291_reg_3077_pp0_iter2_reg;
reg   [8:0] trunc_ln864_299_reg_3087;
wire   [7:0] add_ln859_631_fu_2303_p2;
reg   [7:0] add_ln859_631_reg_3092;
wire   [10:0] add_ln859_582_fu_2325_p2;
reg   [10:0] add_ln859_582_reg_3097;
reg   [10:0] add_ln859_582_reg_3097_pp0_iter2_reg;
reg   [10:0] add_ln859_582_reg_3097_pp0_iter3_reg;
wire   [11:0] add_ln859_645_fu_2331_p2;
reg   [11:0] add_ln859_645_reg_3102;
wire   [9:0] add_ln859_649_fu_2350_p2;
reg   [9:0] add_ln859_649_reg_3107;
wire   [9:0] add_ln859_650_fu_2356_p2;
reg   [9:0] add_ln859_650_reg_3112;
reg   [9:0] add_ln859_650_reg_3112_pp0_iter2_reg;
reg   [11:0] trunc_ln864_282_reg_3117;
reg   [11:0] trunc_ln864_293_reg_3122;
reg   [10:0] trunc_ln864_294_reg_3127;
reg   [10:0] trunc_ln864_296_reg_3132;
reg   [11:0] trunc_ln864_298_reg_3137;
reg   [9:0] trunc_ln864_304_reg_3142;
reg   [9:0] trunc_ln864_305_reg_3147;
reg   [10:0] trunc_ln864_309_reg_3152;
wire   [8:0] add_ln859_628_fu_2516_p2;
reg   [8:0] add_ln859_628_reg_3157;
reg   [8:0] add_ln859_628_reg_3157_pp0_iter3_reg;
wire   [11:0] add_ln1393_29_fu_2542_p2;
reg   [11:0] add_ln1393_29_reg_3162;
reg   [11:0] add_ln1393_29_reg_3162_pp0_iter3_reg;
wire   [10:0] add_ln859_632_fu_2551_p2;
reg   [10:0] add_ln859_632_reg_3167;
wire   [10:0] add_ln859_633_fu_2557_p2;
reg   [10:0] add_ln859_633_reg_3172;
wire   [9:0] add_ln859_634_fu_2563_p2;
reg   [9:0] add_ln859_634_reg_3177;
wire   [7:0] add_ln859_639_fu_2569_p2;
reg   [7:0] add_ln859_639_reg_3182;
wire   [7:0] add_ln1393_31_fu_2575_p2;
reg   [7:0] add_ln1393_31_reg_3187;
wire   [11:0] add_ln859_584_fu_2589_p2;
reg   [11:0] add_ln859_584_reg_3192;
reg   [11:0] add_ln859_584_reg_3192_pp0_iter3_reg;
wire   [8:0] xor_ln859_fu_2595_p2;
reg   [8:0] xor_ln859_reg_3197;
reg   [8:0] trunc_ln_reg_3202;
reg   [9:0] trunc_ln864_292_reg_3207;
wire   [11:0] add_ln859_629_fu_2685_p2;
reg   [11:0] add_ln859_629_reg_3212;
wire   [11:0] add_ln859_578_fu_2706_p2;
reg   [11:0] add_ln859_578_reg_3217;
wire   [12:0] add_ln859_636_fu_2712_p2;
reg   [12:0] add_ln859_636_reg_3222;
wire   [11:0] add_ln859_640_fu_2727_p2;
reg   [11:0] add_ln859_640_reg_3227;
wire   [10:0] add_ln1393_32_fu_2742_p2;
reg   [10:0] add_ln1393_32_reg_3232;
wire   [12:0] add_ln1393_34_fu_2758_p2;
reg   [12:0] add_ln1393_34_reg_3237;
wire   [11:0] add_ln859_652_fu_2776_p2;
reg   [11:0] add_ln859_652_reg_3242;
wire   [4:0] grp_fu_173_p1;
wire    ap_block_pp0_stage0;
wire  signed [7:0] grp_fu_175_p0;
wire   [5:0] grp_fu_175_p1;
wire  signed [5:0] grp_fu_180_p1;
wire  signed [7:0] grp_fu_187_p0;
wire   [5:0] grp_fu_187_p1;
wire  signed [6:0] grp_fu_188_p1;
wire   [6:0] grp_fu_190_p1;
wire  signed [7:0] grp_fu_192_p0;
wire   [4:0] grp_fu_192_p1;
wire  signed [7:0] grp_fu_203_p0;
wire   [4:0] grp_fu_203_p1;
wire   [4:0] mult_V59_fu_1455_p4;
wire  signed [7:0] a_V_fu_1469_p4;
wire   [7:0] tmp_s_fu_1492_p4;
wire   [9:0] shl_ln1319_164_fu_1502_p3;
wire  signed [10:0] sext_ln1319_79_fu_1510_p1;
wire  signed [10:0] sext_ln1319_78_fu_1488_p1;
wire   [10:0] r_V_547_fu_1514_p2;
wire  signed [8:0] sext_ln1319_76_fu_1479_p1;
wire   [8:0] r_V_549_fu_1530_p2;
wire  signed [7:0] a_V_7_fu_1616_p4;
wire   [7:0] tmp_115_fu_1641_p4;
wire   [11:0] shl_ln1319_172_fu_1651_p3;
wire  signed [9:0] shl_ln1319_173_fu_1663_p3;
wire  signed [12:0] sext_ln1319_93_fu_1659_p1;
wire  signed [12:0] sext_ln1319_95_fu_1675_p1;
wire   [12:0] r_V_562_fu_1679_p2;
wire   [8:0] mult_V_115_fu_1695_p3;
wire  signed [10:0] sext_ln1319_94_fu_1671_p1;
wire   [10:0] sub_ln1319_249_fu_1707_p2;
wire  signed [10:0] sext_ln70_1_fu_1631_p1;
wire   [10:0] r_V_564_fu_1713_p2;
wire   [10:0] shl_ln1319_174_fu_1759_p3;
wire  signed [11:0] sext_ln1319_97_fu_1767_p1;
wire   [8:0] trunc_ln864_300_fu_1777_p4;
wire   [12:0] shl_ln1319_176_fu_1791_p3;
wire   [9:0] shl_ln1319_177_fu_1803_p3;
wire  signed [13:0] sext_ln1319_99_fu_1799_p1;
wire  signed [13:0] sext_ln1319_100_fu_1811_p1;
wire   [13:0] r_V_568_fu_1815_p2;
wire  signed [7:0] a_V_9_fu_1831_p4;
wire   [7:0] tmp_117_fu_1851_p4;
wire   [10:0] shl_ln1319_178_fu_1861_p3;
wire  signed [11:0] sext_ln1319_101_fu_1869_p1;
wire  signed [11:0] sext_ln70_4_fu_1847_p1;
wire   [11:0] r_V_570_fu_1873_p2;
wire   [11:0] r_V_571_fu_1889_p2;
wire   [4:0] mult_V_118_fu_1905_p4;
wire  signed [7:0] a_V_6_fu_1919_p4;
wire  signed [8:0] sext_ln1319_104_fu_1938_p1;
wire   [8:0] r_V_574_fu_1942_p2;
wire   [5:0] trunc_ln864_306_fu_1948_p4;
wire   [7:0] tmp_118_fu_1962_p4;
wire   [9:0] shl_ln1319_179_fu_1972_p3;
wire  signed [10:0] sext_ln1319_105_fu_1980_p1;
wire  signed [10:0] sext_ln1319_103_fu_1934_p1;
wire   [10:0] r_V_575_fu_1984_p2;
wire   [10:0] r_V_576_fu_2000_p2;
wire  signed [9:0] sext_ln17_125_fu_1703_p1;
wire  signed [9:0] sext_ln1319_290_fu_1787_p1;
wire  signed [7:0] sext_ln1319_293_fu_1958_p1;
wire  signed [5:0] sext_ln17_fu_1465_p1;
wire  signed [5:0] sext_ln17_128_fu_1915_p1;
wire  signed [8:0] shl_ln1319_165_fu_2037_p3;
wire  signed [9:0] sext_ln1319_82_fu_2052_p1;
wire   [9:0] r_V_550_fu_2056_p2;
wire   [6:0] trunc_ln864_284_fu_2062_p4;
wire   [11:0] shl_ln1319_166_fu_2076_p3;
wire  signed [12:0] sext_ln1319_81_fu_2048_p1;
wire  signed [12:0] sext_ln1319_83_fu_2083_p1;
wire   [12:0] r_V_551_fu_2087_p2;
wire   [9:0] shl_ln1319_167_fu_2103_p3;
wire  signed [12:0] sext_ln1319_84_fu_2110_p1;
wire   [12:0] r_V_552_fu_2114_p2;
wire   [10:0] shl_ln1319_168_fu_2130_p3;
wire  signed [11:0] sext_ln1319_85_fu_2137_p1;
wire  signed [11:0] sext_ln1319_80_fu_2044_p1;
wire   [11:0] r_V_553_fu_2141_p2;
wire   [8:0] trunc_ln864_287_fu_2147_p4;
wire  signed [9:0] shl_ln1319_169_fu_2167_p3;
wire  signed [10:0] sext_ln1319_89_fu_2178_p1;
wire   [10:0] r_V_557_fu_2182_p2;
wire  signed [10:0] sext_ln1319_87_fu_2164_p1;
wire   [10:0] r_V_554_fu_2188_p2;
wire  signed [8:0] sext_ln1319_86_fu_2161_p1;
wire   [8:0] r_V_555_fu_2204_p2;
wire   [5:0] trunc_ln864_289_fu_2210_p4;
wire   [11:0] shl_ln1319_170_fu_2224_p3;
wire  signed [12:0] sext_ln1319_90_fu_2231_p1;
wire  signed [12:0] sext_ln1319_88_fu_2174_p1;
wire   [12:0] r_V_556_fu_2235_p2;
wire   [8:0] shl_ln1319_175_fu_2268_p3;
wire  signed [11:0] sext_ln1319_98_fu_2275_p1;
wire   [11:0] r_V_566_fu_2279_p2;
wire  signed [7:0] sext_ln1319_284_fu_2072_p1;
wire  signed [7:0] sext_ln864_2_fu_2220_p1;
wire  signed [9:0] sext_ln859_255_fu_2312_p1;
wire  signed [9:0] sext_ln1319_292_fu_2297_p1;
wire   [9:0] add_ln859_644_fu_2315_p2;
wire  signed [10:0] sext_ln859_256_fu_2321_p1;
wire  signed [10:0] sext_ln859_253_fu_2309_p1;
wire  signed [11:0] sext_ln1319_289_fu_2265_p1;
wire  signed [11:0] sext_ln17_127_fu_2294_p1;
wire  signed [8:0] sext_ln1319_294_fu_2300_p1;
wire   [8:0] add_ln859_647_fu_2337_p2;
wire  signed [9:0] sext_ln859_258_fu_2347_p1;
wire  signed [9:0] sext_ln859_257_fu_2343_p1;
wire  signed [9:0] sext_ln1319_283_fu_2034_p1;
wire  signed [9:0] trunc_ln864_287_cast_fu_2157_p1;
wire   [14:0] grp_fu_190_p2;
wire  signed [9:0] mult_V_114_fu_2393_p3;
wire   [13:0] shl_ln1319_171_fu_2408_p3;
wire  signed [14:0] sext_ln1319_92_fu_2415_p1;
wire   [14:0] sub_ln1319_246_fu_2419_p2;
wire  signed [14:0] sext_ln17_123_fu_2400_p1;
wire   [14:0] r_V_559_fu_2425_p2;
wire   [13:0] grp_fu_175_p2;
wire   [13:0] grp_fu_187_p2;
wire   [14:0] grp_fu_188_p2;
wire   [12:0] grp_fu_203_p2;
wire   [12:0] grp_fu_192_p2;
wire   [13:0] grp_fu_180_p2;
wire  signed [8:0] sext_ln1319_281_fu_2362_p1;
wire  signed [8:0] sext_ln1319_286_fu_2384_p1;
wire  signed [10:0] sext_ln864_1_fu_2378_p1;
wire  signed [10:0] sext_ln1316_fu_2390_p1;
wire   [10:0] add_ln1393_fu_2522_p2;
wire  signed [8:0] sext_ln1319_96_fu_2477_p1;
wire   [8:0] add_ln1393_28_fu_2532_p2;
wire  signed [11:0] sext_ln1393_19_fu_2538_p1;
wire  signed [11:0] sext_ln1393_18_fu_2528_p1;
wire  signed [10:0] sext_ln859_243_fu_2548_p1;
wire  signed [10:0] sext_ln17_124_fu_2404_p1;
wire  signed [10:0] sext_ln864_4_fu_2451_p1;
wire  signed [10:0] sext_ln1316_2_fu_2480_p1;
wire  signed [9:0] sext_ln1319_291_fu_2483_p1;
wire  signed [7:0] sext_ln17_122_fu_2387_p1;
wire  signed [7:0] sext_ln17_121_fu_2381_p1;
wire  signed [11:0] sext_ln1319_285_fu_2375_p1;
wire  signed [11:0] sext_ln859_259_fu_2586_p1;
wire   [11:0] add_ln859_646_fu_2581_p2;
wire  signed [8:0] sext_ln17_126_fu_2474_p1;
wire   [10:0] shl_ln_fu_2601_p3;
wire  signed [11:0] sext_ln1319_fu_2608_p1;
wire   [8:0] shl_ln1319_s_fu_2618_p3;
wire   [11:0] sub_ln1319_fu_2612_p2;
wire  signed [11:0] sext_ln1319_75_fu_2625_p1;
wire   [11:0] r_V_fu_2629_p2;
wire   [12:0] grp_fu_173_p2;
wire  signed [11:0] sext_ln1319_287_fu_2664_p1;
wire  signed [11:0] sext_ln859_248_fu_2697_p1;
wire  signed [11:0] sext_ln859_247_fu_2694_p1;
wire   [11:0] add_ln859_635_fu_2700_p2;
wire  signed [11:0] sext_ln859_244_fu_2691_p1;
wire  signed [12:0] sext_ln1319_282_fu_2645_p1;
wire  signed [12:0] trunc_ln864_293_cast_fu_2661_p1;
wire  signed [11:0] sext_ln1319_288_fu_2667_p1;
wire  signed [11:0] sext_ln864_6_fu_2673_p1;
wire   [11:0] zext_ln859_fu_2724_p1;
wire   [11:0] add_ln859_638_fu_2718_p2;
wire  signed [10:0] trunc_ln864_291_cast_fu_2648_p1;
wire  signed [10:0] trunc_ln864_305_cast_fu_2676_p1;
wire  signed [10:0] sext_ln1393_20_fu_2739_p1;
wire   [10:0] add_ln1393_30_fu_2733_p2;
wire  signed [8:0] sext_ln1319_295_fu_2679_p1;
wire   [8:0] add_ln1393_33_fu_2748_p2;
wire   [12:0] zext_ln1393_fu_2754_p1;
wire  signed [12:0] sext_ln864_5_fu_2670_p1;
wire   [11:0] zext_ln859_205_fu_2767_p1;
wire  signed [11:0] sext_ln859_fu_2682_p1;
wire   [11:0] add_ln859_651_fu_2770_p2;
wire  signed [11:0] sext_ln859_260_fu_2764_p1;
wire  signed [11:0] sext_ln864_3_fu_2785_p1;
wire   [11:0] add_ln859_630_fu_2791_p2;
wire  signed [11:0] sext_ln859_242_fu_2788_p1;
wire   [11:0] add_ln859_fu_2796_p2;
wire  signed [13:0] sext_ln859_251_fu_2812_p1;
wire  signed [13:0] sext_ln864_fu_2782_p1;
wire  signed [13:0] sext_ln859_252_fu_2821_p1;
wire   [13:0] add_ln859_637_fu_2815_p2;
wire   [13:0] add_ln859_641_fu_2824_p2;
wire  signed [15:0] sext_ln1393_fu_2802_p1;
wire  signed [15:0] sext_ln859_250_fu_2809_p1;
wire  signed [15:0] sext_ln859_249_fu_2837_p1;
wire  signed [15:0] sext_ln859_245_fu_2830_p1;
wire  signed [15:0] sext_ln1393_21_fu_2840_p1;
wire  signed [15:0] sext_ln859_254_fu_2843_p1;
wire  signed [15:0] sext_ln859_239_fu_2806_p1;
wire  signed [15:0] sext_ln859_246_fu_2834_p1;
wire  signed [15:0] sext_ln68_fu_2846_p1;
reg    grp_fu_173_ce;
reg    grp_fu_175_ce;
reg    grp_fu_180_ce;
reg    grp_fu_187_ce;
reg    grp_fu_188_ce;
reg    grp_fu_190_ce;
reg    grp_fu_192_ce;
reg    grp_fu_203_ce;
reg    ap_ce_reg;
reg   [71:0] p_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;

myproject_mul_8s_5ns_13_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_3_0_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_V_2_reg_2954),
    .din1(grp_fu_173_p1),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

myproject_mul_8s_6ns_14_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_3_0_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_175_p0),
    .din1(grp_fu_175_p1),
    .ce(grp_fu_175_ce),
    .dout(grp_fu_175_p2)
);

myproject_mul_8s_6s_14_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_3_0_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_V_6_fu_1919_p4),
    .din1(grp_fu_180_p1),
    .ce(grp_fu_180_ce),
    .dout(grp_fu_180_p2)
);

myproject_mul_8s_6ns_14_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_3_0_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_187_p0),
    .din1(grp_fu_187_p1),
    .ce(grp_fu_187_ce),
    .dout(grp_fu_187_p2)
);

myproject_mul_8s_7s_15_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_8s_7s_15_3_0_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_V_7_fu_1616_p4),
    .din1(grp_fu_188_p1),
    .ce(grp_fu_188_ce),
    .dout(grp_fu_188_p2)
);

myproject_mul_8s_7ns_15_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_8s_7ns_15_3_0_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_V_fu_1469_p4),
    .din1(grp_fu_190_p1),
    .ce(grp_fu_190_ce),
    .dout(grp_fu_190_p2)
);

myproject_mul_8s_5ns_13_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_3_0_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_192_p0),
    .din1(grp_fu_192_p1),
    .ce(grp_fu_192_ce),
    .dout(grp_fu_192_p2)
);

myproject_mul_8s_5ns_13_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_8s_5ns_13_3_0_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_203_p0),
    .din1(grp_fu_203_p1),
    .ce(grp_fu_203_ce),
    .dout(grp_fu_203_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a_V_1_reg_2937 <= {{p_read_int_reg[31:24]}};
        a_V_2_reg_2954 <= {{p_read_int_reg[39:32]}};
        a_V_8_reg_2991 <= {{p_read_int_reg[55:48]}};
        a_V_8_reg_2991_pp0_iter1_reg <= a_V_8_reg_2991;
        add_ln1393_29_reg_3162 <= add_ln1393_29_fu_2542_p2;
        add_ln1393_29_reg_3162_pp0_iter3_reg <= add_ln1393_29_reg_3162;
        add_ln1393_31_reg_3187 <= add_ln1393_31_fu_2575_p2;
        add_ln1393_32_reg_3232 <= add_ln1393_32_fu_2742_p2;
        add_ln1393_34_reg_3237 <= add_ln1393_34_fu_2758_p2;
        add_ln859_578_reg_3217 <= add_ln859_578_fu_2706_p2;
        add_ln859_582_reg_3097 <= add_ln859_582_fu_2325_p2;
        add_ln859_582_reg_3097_pp0_iter2_reg <= add_ln859_582_reg_3097;
        add_ln859_582_reg_3097_pp0_iter3_reg <= add_ln859_582_reg_3097_pp0_iter2_reg;
        add_ln859_584_reg_3192 <= add_ln859_584_fu_2589_p2;
        add_ln859_584_reg_3192_pp0_iter3_reg <= add_ln859_584_reg_3192;
        add_ln859_628_reg_3157 <= add_ln859_628_fu_2516_p2;
        add_ln859_628_reg_3157_pp0_iter3_reg <= add_ln859_628_reg_3157;
        add_ln859_629_reg_3212 <= add_ln859_629_fu_2685_p2;
        add_ln859_631_reg_3092 <= add_ln859_631_fu_2303_p2;
        add_ln859_632_reg_3167 <= add_ln859_632_fu_2551_p2;
        add_ln859_633_reg_3172 <= add_ln859_633_fu_2557_p2;
        add_ln859_634_reg_3177 <= add_ln859_634_fu_2563_p2;
        add_ln859_636_reg_3222 <= add_ln859_636_fu_2712_p2;
        add_ln859_639_reg_3182 <= add_ln859_639_fu_2569_p2;
        add_ln859_640_reg_3227 <= add_ln859_640_fu_2727_p2;
        add_ln859_642_reg_3042 <= add_ln859_642_fu_2016_p2;
        add_ln859_643_reg_3047 <= add_ln859_643_fu_2022_p2;
        add_ln859_645_reg_3102 <= add_ln859_645_fu_2331_p2;
        add_ln859_648_reg_3052 <= add_ln859_648_fu_2028_p2;
        add_ln859_649_reg_3107 <= add_ln859_649_fu_2350_p2;
        add_ln859_650_reg_3112 <= add_ln859_650_fu_2356_p2;
        add_ln859_650_reg_3112_pp0_iter2_reg <= add_ln859_650_reg_3112;
        add_ln859_652_reg_3242 <= add_ln859_652_fu_2776_p2;
        mult_V_113_reg_2949 <= {{p_read_int_reg[31:25]}};
        mult_V_113_reg_2949_pp0_iter1_reg <= mult_V_113_reg_2949;
        mult_V_116_reg_2986 <= {{p_read_int_reg[47:43]}};
        mult_V_116_reg_2986_pp0_iter1_reg <= mult_V_116_reg_2986;
        mult_V_reg_2932 <= {{p_read_int_reg[23:19]}};
        mult_V_reg_2932_pp0_iter1_reg <= mult_V_reg_2932;
        r_V_567_reg_3001[11 : 3] <= r_V_567_fu_1771_p2[11 : 3];
        tmp_112_reg_2924 <= {{p_read_int_reg[23:16]}};
        tmp_113_reg_2943 <= {{p_read_int_reg[31:24]}};
        tmp_114_reg_2959 <= {{p_read_int_reg[39:32]}};
        tmp_114_reg_2959_pp0_iter1_reg <= tmp_114_reg_2959;
        tmp_116_reg_2996 <= {{p_read_int_reg[55:48]}};
        trunc_ln1319_reg_2903 <= trunc_ln1319_fu_1451_p1;
        trunc_ln1319_reg_2903_pp0_iter1_reg <= trunc_ln1319_reg_2903;
        trunc_ln1319_reg_2903_pp0_iter2_reg <= trunc_ln1319_reg_2903_pp0_iter1_reg;
        trunc_ln864_282_reg_3117 <= {{grp_fu_190_p2[14:3]}};
        trunc_ln864_283_reg_2919 <= {{r_V_549_fu_1530_p2[8:3]}};
        trunc_ln864_285_reg_3057 <= {{r_V_551_fu_2087_p2[12:3]}};
        trunc_ln864_286_reg_3062 <= {{r_V_552_fu_2114_p2[12:3]}};
        trunc_ln864_288_reg_3067 <= {{r_V_554_fu_2188_p2[10:3]}};
        trunc_ln864_290_reg_3072 <= {{r_V_556_fu_2235_p2[12:3]}};
        trunc_ln864_291_reg_3077 <= {{r_V_557_fu_2182_p2[10:3]}};
        trunc_ln864_291_reg_3077_pp0_iter2_reg <= trunc_ln864_291_reg_3077;
        trunc_ln864_292_reg_3207 <= {{grp_fu_173_p2[12:3]}};
        trunc_ln864_293_reg_3122 <= {{r_V_559_fu_2425_p2[14:3]}};
        trunc_ln864_294_reg_3127 <= {{grp_fu_175_p2[13:3]}};
        trunc_ln864_295_reg_2976 <= {{r_V_562_fu_1679_p2[12:3]}};
        trunc_ln864_295_reg_2976_pp0_iter1_reg <= trunc_ln864_295_reg_2976;
        trunc_ln864_296_reg_3132 <= {{grp_fu_187_p2[13:3]}};
        trunc_ln864_297_reg_2981 <= {{r_V_564_fu_1713_p2[10:3]}};
        trunc_ln864_298_reg_3137 <= {{grp_fu_188_p2[14:3]}};
        trunc_ln864_299_reg_3087 <= {{r_V_566_fu_2279_p2[11:3]}};
        trunc_ln864_301_reg_3006 <= {{r_V_568_fu_1815_p2[13:3]}};
        trunc_ln864_302_reg_3017 <= {{r_V_570_fu_1873_p2[11:3]}};
        trunc_ln864_302_reg_3017_pp0_iter1_reg <= trunc_ln864_302_reg_3017;
        trunc_ln864_303_reg_3022 <= {{r_V_571_fu_1889_p2[11:3]}};
        trunc_ln864_304_reg_3142 <= {{grp_fu_203_p2[12:3]}};
        trunc_ln864_305_reg_3147 <= {{grp_fu_192_p2[12:3]}};
        trunc_ln864_307_reg_3032 <= {{r_V_575_fu_1984_p2[10:3]}};
        trunc_ln864_308_reg_3037 <= {{r_V_576_fu_2000_p2[10:3]}};
        trunc_ln864_308_reg_3037_pp0_iter1_reg <= trunc_ln864_308_reg_3037;
        trunc_ln864_308_reg_3037_pp0_iter2_reg <= trunc_ln864_308_reg_3037_pp0_iter1_reg;
        trunc_ln864_309_reg_3152 <= {{grp_fu_180_p2[13:3]}};
        trunc_ln864_s_reg_2914 <= {{r_V_547_fu_1514_p2[10:3]}};
        trunc_ln864_s_reg_2914_pp0_iter1_reg <= trunc_ln864_s_reg_2914;
        trunc_ln_reg_3202 <= {{r_V_fu_2629_p2[11:3]}};
        xor_ln859_reg_3197 <= xor_ln859_fu_2595_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln1393_fu_2802_p1;
        ap_return_1_int_reg <= sext_ln859_250_fu_2809_p1;
        ap_return_2_int_reg <= sext_ln859_249_fu_2837_p1;
        ap_return_3_int_reg <= sext_ln859_245_fu_2830_p1;
        ap_return_4_int_reg <= sext_ln1393_21_fu_2840_p1;
        ap_return_5_int_reg <= sext_ln859_254_fu_2843_p1;
        ap_return_6_int_reg <= sext_ln859_239_fu_2806_p1;
        ap_return_7_int_reg <= sext_ln859_246_fu_2834_p1;
        ap_return_8_int_reg <= sext_ln68_fu_2846_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read_int_reg <= p_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln1393_fu_2802_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln859_250_fu_2809_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln859_249_fu_2837_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln859_245_fu_2830_p1;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln1393_21_fu_2840_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln859_254_fu_2843_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = sext_ln859_239_fu_2806_p1;
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = sext_ln859_246_fu_2834_p1;
    end else begin
        ap_return_7 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = sext_ln68_fu_2846_p1;
    end else begin
        ap_return_8 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_173_ce = 1'b1;
    end else begin
        grp_fu_173_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_175_ce = 1'b1;
    end else begin
        grp_fu_175_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_180_ce = 1'b1;
    end else begin
        grp_fu_180_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_187_ce = 1'b1;
    end else begin
        grp_fu_187_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_188_ce = 1'b1;
    end else begin
        grp_fu_188_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_190_ce = 1'b1;
    end else begin
        grp_fu_190_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_192_ce = 1'b1;
    end else begin
        grp_fu_192_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_203_ce = 1'b1;
    end else begin
        grp_fu_203_ce = 1'b0;
    end
end

assign a_V_6_fu_1919_p4 = {{p_read_int_reg[71:64]}};

assign a_V_7_fu_1616_p4 = {{p_read_int_reg[47:40]}};

assign a_V_9_fu_1831_p4 = {{p_read_int_reg[63:56]}};

assign a_V_fu_1469_p4 = {{p_read_int_reg[15:8]}};

assign add_ln1393_28_fu_2532_p2 = ($signed(sext_ln1319_96_fu_2477_p1) + $signed(9'd112));

assign add_ln1393_29_fu_2542_p2 = ($signed(sext_ln1393_19_fu_2538_p1) + $signed(sext_ln1393_18_fu_2528_p1));

assign add_ln1393_30_fu_2733_p2 = ($signed(trunc_ln864_291_cast_fu_2648_p1) + $signed(trunc_ln864_305_cast_fu_2676_p1));

assign add_ln1393_31_fu_2575_p2 = ($signed(sext_ln17_121_fu_2381_p1) + $signed(8'd168));

assign add_ln1393_32_fu_2742_p2 = ($signed(sext_ln1393_20_fu_2739_p1) + $signed(add_ln1393_30_fu_2733_p2));

assign add_ln1393_33_fu_2748_p2 = ($signed(sext_ln1319_295_fu_2679_p1) + $signed(9'd152));

assign add_ln1393_34_fu_2758_p2 = ($signed(zext_ln1393_fu_2754_p1) + $signed(sext_ln864_5_fu_2670_p1));

assign add_ln1393_fu_2522_p2 = ($signed(sext_ln864_1_fu_2378_p1) + $signed(sext_ln1316_fu_2390_p1));

assign add_ln859_578_fu_2706_p2 = ($signed(add_ln859_635_fu_2700_p2) + $signed(sext_ln859_244_fu_2691_p1));

assign add_ln859_582_fu_2325_p2 = ($signed(sext_ln859_256_fu_2321_p1) + $signed(sext_ln859_253_fu_2309_p1));

assign add_ln859_584_fu_2589_p2 = ($signed(sext_ln859_259_fu_2586_p1) + $signed(add_ln859_646_fu_2581_p2));

assign add_ln859_628_fu_2516_p2 = ($signed(sext_ln1319_281_fu_2362_p1) + $signed(sext_ln1319_286_fu_2384_p1));

assign add_ln859_629_fu_2685_p2 = ($signed(sext_ln1319_287_fu_2664_p1) + $signed(12'd152));

assign add_ln859_630_fu_2791_p2 = ($signed(add_ln859_629_reg_3212) + $signed(sext_ln864_3_fu_2785_p1));

assign add_ln859_631_fu_2303_p2 = ($signed(sext_ln1319_284_fu_2072_p1) + $signed(sext_ln864_2_fu_2220_p1));

assign add_ln859_632_fu_2551_p2 = ($signed(sext_ln859_243_fu_2548_p1) + $signed(sext_ln17_124_fu_2404_p1));

assign add_ln859_633_fu_2557_p2 = ($signed(sext_ln864_4_fu_2451_p1) + $signed(sext_ln1316_2_fu_2480_p1));

assign add_ln859_634_fu_2563_p2 = ($signed(sext_ln1319_291_fu_2483_p1) + $signed(10'd184));

assign add_ln859_635_fu_2700_p2 = ($signed(sext_ln859_248_fu_2697_p1) + $signed(sext_ln859_247_fu_2694_p1));

assign add_ln859_636_fu_2712_p2 = ($signed(sext_ln1319_282_fu_2645_p1) + $signed(trunc_ln864_293_cast_fu_2661_p1));

assign add_ln859_637_fu_2815_p2 = ($signed(sext_ln859_251_fu_2812_p1) + $signed(sext_ln864_fu_2782_p1));

assign add_ln859_638_fu_2718_p2 = ($signed(sext_ln1319_288_fu_2667_p1) + $signed(sext_ln864_6_fu_2673_p1));

assign add_ln859_639_fu_2569_p2 = ($signed(sext_ln17_122_fu_2387_p1) + $signed(8'd104));

assign add_ln859_640_fu_2727_p2 = (zext_ln859_fu_2724_p1 + add_ln859_638_fu_2718_p2);

assign add_ln859_641_fu_2824_p2 = ($signed(sext_ln859_252_fu_2821_p1) + $signed(add_ln859_637_fu_2815_p2));

assign add_ln859_642_fu_2016_p2 = ($signed(sext_ln17_125_fu_1703_p1) + $signed(sext_ln1319_290_fu_1787_p1));

assign add_ln859_643_fu_2022_p2 = ($signed(sext_ln1319_293_fu_1958_p1) + $signed(8'd160));

assign add_ln859_644_fu_2315_p2 = ($signed(sext_ln859_255_fu_2312_p1) + $signed(sext_ln1319_292_fu_2297_p1));

assign add_ln859_645_fu_2331_p2 = ($signed(sext_ln1319_289_fu_2265_p1) + $signed(sext_ln17_127_fu_2294_p1));

assign add_ln859_646_fu_2581_p2 = ($signed(add_ln859_645_reg_3102) + $signed(sext_ln1319_285_fu_2375_p1));

assign add_ln859_647_fu_2337_p2 = ($signed(sext_ln1319_294_fu_2300_p1) + $signed(9'd400));

assign add_ln859_648_fu_2028_p2 = ($signed(sext_ln17_fu_1465_p1) + $signed(sext_ln17_128_fu_1915_p1));

assign add_ln859_649_fu_2350_p2 = ($signed(sext_ln859_258_fu_2347_p1) + $signed(sext_ln859_257_fu_2343_p1));

assign add_ln859_650_fu_2356_p2 = ($signed(sext_ln1319_283_fu_2034_p1) + $signed(trunc_ln864_287_cast_fu_2157_p1));

assign add_ln859_651_fu_2770_p2 = ($signed(zext_ln859_205_fu_2767_p1) + $signed(sext_ln859_fu_2682_p1));

assign add_ln859_652_fu_2776_p2 = ($signed(add_ln859_651_fu_2770_p2) + $signed(sext_ln859_260_fu_2764_p1));

assign add_ln859_fu_2796_p2 = ($signed(add_ln859_630_fu_2791_p2) + $signed(sext_ln859_242_fu_2788_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign grp_fu_173_p1 = 13'd13;

assign grp_fu_175_p0 = sext_ln70_2_fu_1635_p1;

assign grp_fu_175_p1 = 14'd23;

assign grp_fu_180_p1 = 14'd16359;

assign grp_fu_187_p0 = sext_ln70_2_fu_1635_p1;

assign grp_fu_187_p1 = 14'd26;

assign grp_fu_188_p1 = 15'd32727;

assign grp_fu_190_p1 = 15'd41;

assign grp_fu_192_p0 = sext_ln70_3_fu_1841_p1;

assign grp_fu_192_p1 = 13'd13;

assign grp_fu_203_p0 = sext_ln70_3_fu_1841_p1;

assign grp_fu_203_p1 = 13'd11;

assign mult_V59_fu_1455_p4 = {{p_read_int_reg[7:3]}};

assign mult_V_114_fu_2393_p3 = {{tmp_114_reg_2959_pp0_iter1_reg}, {2'd0}};

assign mult_V_115_fu_1695_p3 = {{tmp_115_fu_1641_p4}, {1'd0}};

assign mult_V_118_fu_1905_p4 = {{p_read_int_reg[63:59]}};

assign r_V_547_fu_1514_p2 = ($signed(sext_ln1319_79_fu_1510_p1) + $signed(sext_ln1319_78_fu_1488_p1));

assign r_V_549_fu_1530_p2 = ($signed(9'd0) - $signed(sext_ln1319_76_fu_1479_p1));

assign r_V_550_fu_2056_p2 = ($signed(10'd0) - $signed(sext_ln1319_82_fu_2052_p1));

assign r_V_551_fu_2087_p2 = ($signed(sext_ln1319_81_fu_2048_p1) - $signed(sext_ln1319_83_fu_2083_p1));

assign r_V_552_fu_2114_p2 = ($signed(sext_ln1319_83_fu_2083_p1) - $signed(sext_ln1319_84_fu_2110_p1));

assign r_V_553_fu_2141_p2 = ($signed(sext_ln1319_85_fu_2137_p1) + $signed(sext_ln1319_80_fu_2044_p1));

assign r_V_554_fu_2188_p2 = ($signed(r_V_557_fu_2182_p2) - $signed(sext_ln1319_87_fu_2164_p1));

assign r_V_555_fu_2204_p2 = ($signed(9'd0) - $signed(sext_ln1319_86_fu_2161_p1));

assign r_V_556_fu_2235_p2 = ($signed(sext_ln1319_90_fu_2231_p1) - $signed(sext_ln1319_88_fu_2174_p1));

assign r_V_557_fu_2182_p2 = ($signed(11'd0) - $signed(sext_ln1319_89_fu_2178_p1));

assign r_V_559_fu_2425_p2 = ($signed(sub_ln1319_246_fu_2419_p2) - $signed(sext_ln17_123_fu_2400_p1));

assign r_V_562_fu_1679_p2 = ($signed(sext_ln1319_93_fu_1659_p1) - $signed(sext_ln1319_95_fu_1675_p1));

assign r_V_564_fu_1713_p2 = ($signed(sub_ln1319_249_fu_1707_p2) - $signed(sext_ln70_1_fu_1631_p1));

assign r_V_566_fu_2279_p2 = ($signed(r_V_567_reg_3001) - $signed(sext_ln1319_98_fu_2275_p1));

assign r_V_567_fu_1771_p2 = ($signed(12'd0) - $signed(sext_ln1319_97_fu_1767_p1));

assign r_V_568_fu_1815_p2 = ($signed(sext_ln1319_99_fu_1799_p1) + $signed(sext_ln1319_100_fu_1811_p1));

assign r_V_570_fu_1873_p2 = ($signed(sext_ln1319_101_fu_1869_p1) + $signed(sext_ln70_4_fu_1847_p1));

assign r_V_571_fu_1889_p2 = ($signed(12'd0) - $signed(sext_ln1319_101_fu_1869_p1));

assign r_V_574_fu_1942_p2 = ($signed(9'd0) - $signed(sext_ln1319_104_fu_1938_p1));

assign r_V_575_fu_1984_p2 = ($signed(sext_ln1319_105_fu_1980_p1) - $signed(sext_ln1319_103_fu_1934_p1));

assign r_V_576_fu_2000_p2 = ($signed(11'd0) - $signed(sext_ln1319_105_fu_1980_p1));

assign r_V_fu_2629_p2 = ($signed(sub_ln1319_fu_2612_p2) - $signed(sext_ln1319_75_fu_2625_p1));

assign sext_ln1316_2_fu_2480_p1 = $signed(trunc_ln864_299_reg_3087);

assign sext_ln1316_fu_2390_p1 = $signed(trunc_ln864_290_reg_3072);

assign sext_ln1319_100_fu_1811_p1 = $signed(shl_ln1319_177_fu_1803_p3);

assign sext_ln1319_101_fu_1869_p1 = $signed(shl_ln1319_178_fu_1861_p3);

assign sext_ln1319_103_fu_1934_p1 = a_V_6_fu_1919_p4;

assign sext_ln1319_104_fu_1938_p1 = a_V_6_fu_1919_p4;

assign sext_ln1319_105_fu_1980_p1 = $signed(shl_ln1319_179_fu_1972_p3);

assign sext_ln1319_281_fu_2362_p1 = $signed(trunc_ln864_s_reg_2914_pp0_iter1_reg);

assign sext_ln1319_282_fu_2645_p1 = $signed(trunc_ln864_282_reg_3117);

assign sext_ln1319_283_fu_2034_p1 = $signed(trunc_ln864_283_reg_2919);

assign sext_ln1319_284_fu_2072_p1 = $signed(trunc_ln864_284_fu_2062_p4);

assign sext_ln1319_285_fu_2375_p1 = $signed(trunc_ln864_285_reg_3057);

assign sext_ln1319_286_fu_2384_p1 = $signed(trunc_ln864_288_reg_3067);

assign sext_ln1319_287_fu_2664_p1 = $signed(trunc_ln864_294_reg_3127);

assign sext_ln1319_288_fu_2667_p1 = $signed(trunc_ln864_296_reg_3132);

assign sext_ln1319_289_fu_2265_p1 = $signed(trunc_ln864_297_reg_2981);

assign sext_ln1319_290_fu_1787_p1 = $signed(trunc_ln864_300_fu_1777_p4);

assign sext_ln1319_291_fu_2483_p1 = $signed(trunc_ln864_302_reg_3017_pp0_iter1_reg);

assign sext_ln1319_292_fu_2297_p1 = $signed(trunc_ln864_303_reg_3022);

assign sext_ln1319_293_fu_1958_p1 = $signed(trunc_ln864_306_fu_1948_p4);

assign sext_ln1319_294_fu_2300_p1 = $signed(trunc_ln864_307_reg_3032);

assign sext_ln1319_295_fu_2679_p1 = $signed(trunc_ln864_308_reg_3037_pp0_iter2_reg);

assign sext_ln1319_75_fu_2625_p1 = $signed(shl_ln1319_s_fu_2618_p3);

assign sext_ln1319_76_fu_1479_p1 = a_V_fu_1469_p4;

assign sext_ln1319_78_fu_1488_p1 = a_V_fu_1469_p4;

assign sext_ln1319_79_fu_1510_p1 = $signed(shl_ln1319_164_fu_1502_p3);

assign sext_ln1319_80_fu_2044_p1 = shl_ln1319_165_fu_2037_p3;

assign sext_ln1319_81_fu_2048_p1 = shl_ln1319_165_fu_2037_p3;

assign sext_ln1319_82_fu_2052_p1 = shl_ln1319_165_fu_2037_p3;

assign sext_ln1319_83_fu_2083_p1 = $signed(shl_ln1319_166_fu_2076_p3);

assign sext_ln1319_84_fu_2110_p1 = $signed(shl_ln1319_167_fu_2103_p3);

assign sext_ln1319_85_fu_2137_p1 = $signed(shl_ln1319_168_fu_2130_p3);

assign sext_ln1319_86_fu_2161_p1 = a_V_1_reg_2937;

assign sext_ln1319_87_fu_2164_p1 = a_V_1_reg_2937;

assign sext_ln1319_88_fu_2174_p1 = shl_ln1319_169_fu_2167_p3;

assign sext_ln1319_89_fu_2178_p1 = shl_ln1319_169_fu_2167_p3;

assign sext_ln1319_90_fu_2231_p1 = $signed(shl_ln1319_170_fu_2224_p3);

assign sext_ln1319_92_fu_2415_p1 = $signed(shl_ln1319_171_fu_2408_p3);

assign sext_ln1319_93_fu_1659_p1 = $signed(shl_ln1319_172_fu_1651_p3);

assign sext_ln1319_94_fu_1671_p1 = shl_ln1319_173_fu_1663_p3;

assign sext_ln1319_95_fu_1675_p1 = shl_ln1319_173_fu_1663_p3;

assign sext_ln1319_96_fu_2477_p1 = $signed(a_V_8_reg_2991_pp0_iter1_reg);

assign sext_ln1319_97_fu_1767_p1 = $signed(shl_ln1319_174_fu_1759_p3);

assign sext_ln1319_98_fu_2275_p1 = $signed(shl_ln1319_175_fu_2268_p3);

assign sext_ln1319_99_fu_1799_p1 = $signed(shl_ln1319_176_fu_1791_p3);

assign sext_ln1319_fu_2608_p1 = $signed(shl_ln_fu_2601_p3);

assign sext_ln1393_18_fu_2528_p1 = $signed(add_ln1393_fu_2522_p2);

assign sext_ln1393_19_fu_2538_p1 = $signed(add_ln1393_28_fu_2532_p2);

assign sext_ln1393_20_fu_2739_p1 = $signed(add_ln1393_31_reg_3187);

assign sext_ln1393_21_fu_2840_p1 = $signed(add_ln859_584_reg_3192_pp0_iter3_reg);

assign sext_ln1393_fu_2802_p1 = $signed(add_ln859_fu_2796_p2);

assign sext_ln17_121_fu_2381_p1 = $signed(mult_V_reg_2932_pp0_iter1_reg);

assign sext_ln17_122_fu_2387_p1 = $signed(mult_V_113_reg_2949_pp0_iter1_reg);

assign sext_ln17_123_fu_2400_p1 = mult_V_114_fu_2393_p3;

assign sext_ln17_124_fu_2404_p1 = mult_V_114_fu_2393_p3;

assign sext_ln17_125_fu_1703_p1 = $signed(mult_V_115_fu_1695_p3);

assign sext_ln17_126_fu_2474_p1 = $signed(mult_V_116_reg_2986_pp0_iter1_reg);

assign sext_ln17_127_fu_2294_p1 = $signed(trunc_ln864_301_reg_3006);

assign sext_ln17_128_fu_1915_p1 = $signed(mult_V_118_fu_1905_p4);

assign sext_ln17_fu_1465_p1 = $signed(mult_V59_fu_1455_p4);

assign sext_ln68_fu_2846_p1 = $signed(add_ln859_652_reg_3242);

assign sext_ln70_1_fu_1631_p1 = a_V_7_fu_1616_p4;

assign sext_ln70_2_fu_1635_p1 = a_V_7_fu_1616_p4;

assign sext_ln70_3_fu_1841_p1 = a_V_9_fu_1831_p4;

assign sext_ln70_4_fu_1847_p1 = a_V_9_fu_1831_p4;

assign sext_ln859_239_fu_2806_p1 = $signed(add_ln1393_29_reg_3162_pp0_iter3_reg);

assign sext_ln859_242_fu_2788_p1 = $signed(add_ln859_628_reg_3157_pp0_iter3_reg);

assign sext_ln859_243_fu_2548_p1 = $signed(add_ln859_631_reg_3092);

assign sext_ln859_244_fu_2691_p1 = $signed(add_ln859_632_reg_3167);

assign sext_ln859_245_fu_2830_p1 = $signed(add_ln859_641_fu_2824_p2);

assign sext_ln859_246_fu_2834_p1 = $signed(add_ln1393_32_reg_3232);

assign sext_ln859_247_fu_2694_p1 = $signed(add_ln859_633_reg_3172);

assign sext_ln859_248_fu_2697_p1 = $signed(add_ln859_634_reg_3177);

assign sext_ln859_249_fu_2837_p1 = $signed(add_ln859_582_reg_3097_pp0_iter3_reg);

assign sext_ln859_250_fu_2809_p1 = $signed(add_ln859_578_reg_3217);

assign sext_ln859_251_fu_2812_p1 = $signed(add_ln859_636_reg_3222);

assign sext_ln859_252_fu_2821_p1 = $signed(add_ln859_640_reg_3227);

assign sext_ln859_253_fu_2309_p1 = $signed(add_ln859_642_reg_3042);

assign sext_ln859_254_fu_2843_p1 = $signed(add_ln1393_34_reg_3237);

assign sext_ln859_255_fu_2312_p1 = $signed(add_ln859_643_reg_3047);

assign sext_ln859_256_fu_2321_p1 = $signed(add_ln859_644_fu_2315_p2);

assign sext_ln859_257_fu_2343_p1 = $signed(add_ln859_647_fu_2337_p2);

assign sext_ln859_258_fu_2347_p1 = $signed(add_ln859_648_reg_3052);

assign sext_ln859_259_fu_2586_p1 = $signed(add_ln859_649_reg_3107);

assign sext_ln859_260_fu_2764_p1 = $signed(add_ln859_650_reg_3112_pp0_iter2_reg);

assign sext_ln859_fu_2682_p1 = $signed(trunc_ln864_309_reg_3152);

assign sext_ln864_1_fu_2378_p1 = $signed(trunc_ln864_286_reg_3062);

assign sext_ln864_2_fu_2220_p1 = $signed(trunc_ln864_289_fu_2210_p4);

assign sext_ln864_3_fu_2785_p1 = $signed(trunc_ln864_292_reg_3207);

assign sext_ln864_4_fu_2451_p1 = $signed(trunc_ln864_295_reg_2976_pp0_iter1_reg);

assign sext_ln864_5_fu_2670_p1 = $signed(trunc_ln864_298_reg_3137);

assign sext_ln864_6_fu_2673_p1 = $signed(trunc_ln864_304_reg_3142);

assign sext_ln864_fu_2782_p1 = $signed(trunc_ln_reg_3202);

assign shl_ln1319_164_fu_1502_p3 = {{tmp_s_fu_1492_p4}, {2'd0}};

assign shl_ln1319_165_fu_2037_p3 = {{tmp_112_reg_2924}, {1'd0}};

assign shl_ln1319_166_fu_2076_p3 = {{tmp_112_reg_2924}, {4'd0}};

assign shl_ln1319_167_fu_2103_p3 = {{tmp_112_reg_2924}, {2'd0}};

assign shl_ln1319_168_fu_2130_p3 = {{tmp_112_reg_2924}, {3'd0}};

assign shl_ln1319_169_fu_2167_p3 = {{tmp_113_reg_2943}, {2'd0}};

assign shl_ln1319_170_fu_2224_p3 = {{tmp_113_reg_2943}, {4'd0}};

assign shl_ln1319_171_fu_2408_p3 = {{tmp_114_reg_2959_pp0_iter1_reg}, {6'd0}};

assign shl_ln1319_172_fu_1651_p3 = {{tmp_115_fu_1641_p4}, {4'd0}};

assign shl_ln1319_173_fu_1663_p3 = {{tmp_115_fu_1641_p4}, {2'd0}};

assign shl_ln1319_174_fu_1759_p3 = {{tmp_116_fu_1749_p4}, {3'd0}};

assign shl_ln1319_175_fu_2268_p3 = {{tmp_116_reg_2996}, {1'd0}};

assign shl_ln1319_176_fu_1791_p3 = {{tmp_116_fu_1749_p4}, {5'd0}};

assign shl_ln1319_177_fu_1803_p3 = {{tmp_116_fu_1749_p4}, {2'd0}};

assign shl_ln1319_178_fu_1861_p3 = {{tmp_117_fu_1851_p4}, {3'd0}};

assign shl_ln1319_179_fu_1972_p3 = {{tmp_118_fu_1962_p4}, {2'd0}};

assign shl_ln1319_s_fu_2618_p3 = {{trunc_ln1319_reg_2903_pp0_iter2_reg}, {1'd0}};

assign shl_ln_fu_2601_p3 = {{trunc_ln1319_reg_2903_pp0_iter2_reg}, {3'd0}};

assign sub_ln1319_246_fu_2419_p2 = ($signed(15'd0) - $signed(sext_ln1319_92_fu_2415_p1));

assign sub_ln1319_249_fu_1707_p2 = ($signed(11'd0) - $signed(sext_ln1319_94_fu_1671_p1));

assign sub_ln1319_fu_2612_p2 = ($signed(12'd0) - $signed(sext_ln1319_fu_2608_p1));

assign tmp_115_fu_1641_p4 = {{p_read_int_reg[47:40]}};

assign tmp_116_fu_1749_p4 = {{p_read_int_reg[55:48]}};

assign tmp_117_fu_1851_p4 = {{p_read_int_reg[63:56]}};

assign tmp_118_fu_1962_p4 = {{p_read_int_reg[71:64]}};

assign tmp_s_fu_1492_p4 = {{p_read_int_reg[15:8]}};

assign trunc_ln1319_fu_1451_p1 = p_read_int_reg[7:0];

assign trunc_ln864_284_fu_2062_p4 = {{r_V_550_fu_2056_p2[9:3]}};

assign trunc_ln864_287_cast_fu_2157_p1 = $signed(trunc_ln864_287_fu_2147_p4);

assign trunc_ln864_287_fu_2147_p4 = {{r_V_553_fu_2141_p2[11:3]}};

assign trunc_ln864_289_fu_2210_p4 = {{r_V_555_fu_2204_p2[8:3]}};

assign trunc_ln864_291_cast_fu_2648_p1 = $signed(trunc_ln864_291_reg_3077_pp0_iter2_reg);

assign trunc_ln864_293_cast_fu_2661_p1 = $signed(trunc_ln864_293_reg_3122);

assign trunc_ln864_300_fu_1777_p4 = {{r_V_567_fu_1771_p2[11:3]}};

assign trunc_ln864_305_cast_fu_2676_p1 = $signed(trunc_ln864_305_reg_3147);

assign trunc_ln864_306_fu_1948_p4 = {{r_V_574_fu_1942_p2[8:3]}};

assign xor_ln859_fu_2595_p2 = (sext_ln17_126_fu_2474_p1 ^ 9'd256);

assign zext_ln1393_fu_2754_p1 = add_ln1393_33_fu_2748_p2;

assign zext_ln859_205_fu_2767_p1 = xor_ln859_reg_3197;

assign zext_ln859_fu_2724_p1 = add_ln859_639_reg_3182;

always @ (posedge ap_clk) begin
    r_V_567_reg_3001[2:0] <= 3'b000;
end

endmodule //myproject_dense_latency_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_config2_s
