// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config4_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;

wire   [0:0] p_Result_s_fu_130_p3;
wire   [0:0] r_fu_146_p1;
wire   [0:0] or_ln420_fu_158_p2;
wire   [0:0] p_Result_372_fu_138_p3;
wire   [0:0] and_ln420_fu_164_p2;
wire   [7:0] p_Val2_s_fu_120_p4;
wire   [7:0] zext_ln423_fu_170_p1;
wire   [5:0] tmp21_fu_180_p4;
wire   [7:0] p_Val2_101_fu_174_p2;
wire   [0:0] tmp_fu_202_p3;
wire   [0:0] Range1_all_zeros_fu_196_p2;
wire   [0:0] Range1_all_ones_fu_190_p2;
wire   [0:0] p_Result_373_fu_150_p3;
wire   [0:0] select_ln934_fu_210_p3;
wire   [0:0] deleted_zeros_fu_218_p3;
wire   [0:0] icmp_ln1695_fu_114_p2;
wire   [7:0] select_ln348_fu_226_p3;
wire   [0:0] p_Result_350_fu_258_p3;
wire   [0:0] r_31_fu_274_p1;
wire   [0:0] or_ln420_31_fu_286_p2;
wire   [0:0] p_Result_374_fu_266_p3;
wire   [0:0] and_ln420_31_fu_292_p2;
wire   [7:0] p_Val2_102_fu_248_p4;
wire   [7:0] zext_ln423_31_fu_298_p1;
wire   [5:0] tmp_28_fu_308_p4;
wire   [7:0] p_Val2_103_fu_302_p2;
wire   [0:0] tmp_243_fu_330_p3;
wire   [0:0] Range1_all_zeros_31_fu_324_p2;
wire   [0:0] Range1_all_ones_31_fu_318_p2;
wire   [0:0] p_Result_375_fu_278_p3;
wire   [0:0] select_ln934_31_fu_338_p3;
wire   [0:0] deleted_zeros_31_fu_346_p3;
wire   [0:0] icmp_ln1695_31_fu_242_p2;
wire   [7:0] select_ln348_31_fu_354_p3;
wire   [0:0] p_Result_353_fu_386_p3;
wire   [0:0] r_32_fu_402_p1;
wire   [0:0] or_ln420_32_fu_414_p2;
wire   [0:0] p_Result_376_fu_394_p3;
wire   [0:0] and_ln420_32_fu_420_p2;
wire   [7:0] p_Val2_104_fu_376_p4;
wire   [7:0] zext_ln423_32_fu_426_p1;
wire   [5:0] tmp_s_fu_436_p4;
wire   [7:0] p_Val2_105_fu_430_p2;
wire   [0:0] tmp_247_fu_458_p3;
wire   [0:0] Range1_all_zeros_32_fu_452_p2;
wire   [0:0] Range1_all_ones_32_fu_446_p2;
wire   [0:0] p_Result_377_fu_406_p3;
wire   [0:0] select_ln934_32_fu_466_p3;
wire   [0:0] deleted_zeros_32_fu_474_p3;
wire   [0:0] icmp_ln1695_32_fu_370_p2;
wire   [7:0] select_ln348_32_fu_482_p3;
wire   [0:0] p_Result_356_fu_514_p3;
wire   [0:0] r_33_fu_530_p1;
wire   [0:0] or_ln420_33_fu_542_p2;
wire   [0:0] p_Result_378_fu_522_p3;
wire   [0:0] and_ln420_33_fu_548_p2;
wire   [7:0] p_Val2_106_fu_504_p4;
wire   [7:0] zext_ln423_33_fu_554_p1;
wire   [5:0] tmp_67_fu_564_p4;
wire   [7:0] p_Val2_107_fu_558_p2;
wire   [0:0] tmp_251_fu_586_p3;
wire   [0:0] Range1_all_zeros_33_fu_580_p2;
wire   [0:0] Range1_all_ones_33_fu_574_p2;
wire   [0:0] p_Result_379_fu_534_p3;
wire   [0:0] select_ln934_33_fu_594_p3;
wire   [0:0] deleted_zeros_33_fu_602_p3;
wire   [0:0] icmp_ln1695_33_fu_498_p2;
wire   [7:0] select_ln348_33_fu_610_p3;
wire   [0:0] p_Result_359_fu_642_p3;
wire   [0:0] r_34_fu_658_p1;
wire   [0:0] or_ln420_34_fu_670_p2;
wire   [0:0] p_Result_380_fu_650_p3;
wire   [0:0] and_ln420_34_fu_676_p2;
wire   [7:0] p_Val2_108_fu_632_p4;
wire   [7:0] zext_ln423_34_fu_682_p1;
wire   [5:0] tmp_68_fu_692_p4;
wire   [7:0] p_Val2_109_fu_686_p2;
wire   [0:0] tmp_255_fu_714_p3;
wire   [0:0] Range1_all_zeros_34_fu_708_p2;
wire   [0:0] Range1_all_ones_34_fu_702_p2;
wire   [0:0] p_Result_381_fu_662_p3;
wire   [0:0] select_ln934_34_fu_722_p3;
wire   [0:0] deleted_zeros_34_fu_730_p3;
wire   [0:0] icmp_ln1695_34_fu_626_p2;
wire   [7:0] select_ln348_34_fu_738_p3;
wire   [0:0] p_Result_362_fu_770_p3;
wire   [0:0] r_35_fu_786_p1;
wire   [0:0] or_ln420_35_fu_798_p2;
wire   [0:0] p_Result_382_fu_778_p3;
wire   [0:0] and_ln420_35_fu_804_p2;
wire   [7:0] p_Val2_110_fu_760_p4;
wire   [7:0] zext_ln423_35_fu_810_p1;
wire   [5:0] tmp_69_fu_820_p4;
wire   [7:0] p_Val2_111_fu_814_p2;
wire   [0:0] tmp_259_fu_842_p3;
wire   [0:0] Range1_all_zeros_35_fu_836_p2;
wire   [0:0] Range1_all_ones_35_fu_830_p2;
wire   [0:0] p_Result_383_fu_790_p3;
wire   [0:0] select_ln934_35_fu_850_p3;
wire   [0:0] deleted_zeros_35_fu_858_p3;
wire   [0:0] icmp_ln1695_35_fu_754_p2;
wire   [7:0] select_ln348_35_fu_866_p3;
wire   [0:0] p_Result_365_fu_898_p3;
wire   [0:0] r_36_fu_914_p1;
wire   [0:0] or_ln420_36_fu_926_p2;
wire   [0:0] p_Result_384_fu_906_p3;
wire   [0:0] and_ln420_36_fu_932_p2;
wire   [7:0] p_Val2_112_fu_888_p4;
wire   [7:0] zext_ln423_36_fu_938_p1;
wire   [5:0] tmp_70_fu_948_p4;
wire   [7:0] p_Val2_113_fu_942_p2;
wire   [0:0] tmp_263_fu_970_p3;
wire   [0:0] Range1_all_zeros_36_fu_964_p2;
wire   [0:0] Range1_all_ones_36_fu_958_p2;
wire   [0:0] p_Result_385_fu_918_p3;
wire   [0:0] select_ln934_36_fu_978_p3;
wire   [0:0] deleted_zeros_36_fu_986_p3;
wire   [0:0] icmp_ln1695_36_fu_882_p2;
wire   [7:0] select_ln348_36_fu_994_p3;
wire   [0:0] p_Result_368_fu_1026_p3;
wire   [0:0] r_37_fu_1042_p1;
wire   [0:0] or_ln420_37_fu_1054_p2;
wire   [0:0] p_Result_386_fu_1034_p3;
wire   [0:0] and_ln420_37_fu_1060_p2;
wire   [7:0] p_Val2_114_fu_1016_p4;
wire   [7:0] zext_ln423_37_fu_1066_p1;
wire   [5:0] tmp_71_fu_1076_p4;
wire   [7:0] p_Val2_115_fu_1070_p2;
wire   [0:0] tmp_267_fu_1098_p3;
wire   [0:0] Range1_all_zeros_37_fu_1092_p2;
wire   [0:0] Range1_all_ones_37_fu_1086_p2;
wire   [0:0] p_Result_387_fu_1046_p3;
wire   [0:0] select_ln934_37_fu_1106_p3;
wire   [0:0] deleted_zeros_37_fu_1114_p3;
wire   [0:0] icmp_ln1695_37_fu_1010_p2;
wire   [7:0] select_ln348_37_fu_1122_p3;
wire   [0:0] p_Result_371_fu_1154_p3;
wire   [0:0] r_38_fu_1170_p1;
wire   [0:0] or_ln420_38_fu_1182_p2;
wire   [0:0] p_Result_388_fu_1162_p3;
wire   [0:0] and_ln420_38_fu_1188_p2;
wire   [7:0] p_Val2_116_fu_1144_p4;
wire   [7:0] zext_ln423_38_fu_1194_p1;
wire   [5:0] tmp_72_fu_1204_p4;
wire   [7:0] p_Val2_117_fu_1198_p2;
wire   [0:0] tmp_271_fu_1226_p3;
wire   [0:0] Range1_all_zeros_38_fu_1220_p2;
wire   [0:0] Range1_all_ones_38_fu_1214_p2;
wire   [0:0] p_Result_389_fu_1174_p3;
wire   [0:0] select_ln934_38_fu_1234_p3;
wire   [0:0] deleted_zeros_38_fu_1242_p3;
wire   [0:0] icmp_ln1695_38_fu_1138_p2;
wire   [7:0] select_ln348_38_fu_1250_p3;
wire   [7:0] select_ln1695_fu_234_p3;
wire   [7:0] select_ln1695_31_fu_362_p3;
wire   [7:0] select_ln1695_32_fu_490_p3;
wire   [7:0] select_ln1695_33_fu_618_p3;
wire   [7:0] select_ln1695_34_fu_746_p3;
wire   [7:0] select_ln1695_35_fu_874_p3;
wire   [7:0] select_ln1695_36_fu_1002_p3;
wire   [7:0] select_ln1695_37_fu_1130_p3;
wire   [7:0] select_ln1695_38_fu_1258_p3;
wire    ap_ce_reg;

assign Range1_all_ones_31_fu_318_p2 = ((tmp_28_fu_308_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_32_fu_446_p2 = ((tmp_s_fu_436_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_33_fu_574_p2 = ((tmp_67_fu_564_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_34_fu_702_p2 = ((tmp_68_fu_692_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_35_fu_830_p2 = ((tmp_69_fu_820_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_36_fu_958_p2 = ((tmp_70_fu_948_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_37_fu_1086_p2 = ((tmp_71_fu_1076_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_38_fu_1214_p2 = ((tmp_72_fu_1204_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_190_p2 = ((tmp21_fu_180_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_31_fu_324_p2 = ((tmp_28_fu_308_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_32_fu_452_p2 = ((tmp_s_fu_436_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_33_fu_580_p2 = ((tmp_67_fu_564_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_34_fu_708_p2 = ((tmp_68_fu_692_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_35_fu_836_p2 = ((tmp_69_fu_820_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_36_fu_964_p2 = ((tmp_70_fu_948_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_37_fu_1092_p2 = ((tmp_71_fu_1076_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_38_fu_1220_p2 = ((tmp_72_fu_1204_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_196_p2 = ((tmp21_fu_180_p4 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln420_31_fu_292_p2 = (p_Result_374_fu_266_p3 & or_ln420_31_fu_286_p2);

assign and_ln420_32_fu_420_p2 = (p_Result_376_fu_394_p3 & or_ln420_32_fu_414_p2);

assign and_ln420_33_fu_548_p2 = (p_Result_378_fu_522_p3 & or_ln420_33_fu_542_p2);

assign and_ln420_34_fu_676_p2 = (p_Result_380_fu_650_p3 & or_ln420_34_fu_670_p2);

assign and_ln420_35_fu_804_p2 = (p_Result_382_fu_778_p3 & or_ln420_35_fu_798_p2);

assign and_ln420_36_fu_932_p2 = (p_Result_384_fu_906_p3 & or_ln420_36_fu_926_p2);

assign and_ln420_37_fu_1060_p2 = (p_Result_386_fu_1034_p3 & or_ln420_37_fu_1054_p2);

assign and_ln420_38_fu_1188_p2 = (p_Result_388_fu_1162_p3 & or_ln420_38_fu_1182_p2);

assign and_ln420_fu_164_p2 = (p_Result_372_fu_138_p3 & or_ln420_fu_158_p2);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1695_fu_234_p3;

assign ap_return_1 = select_ln1695_31_fu_362_p3;

assign ap_return_2 = select_ln1695_32_fu_490_p3;

assign ap_return_3 = select_ln1695_33_fu_618_p3;

assign ap_return_4 = select_ln1695_34_fu_746_p3;

assign ap_return_5 = select_ln1695_35_fu_874_p3;

assign ap_return_6 = select_ln1695_36_fu_1002_p3;

assign ap_return_7 = select_ln1695_37_fu_1130_p3;

assign ap_return_8 = select_ln1695_38_fu_1258_p3;

assign deleted_zeros_31_fu_346_p3 = ((p_Result_375_fu_278_p3[0:0] == 1'b1) ? select_ln934_31_fu_338_p3 : Range1_all_zeros_31_fu_324_p2);

assign deleted_zeros_32_fu_474_p3 = ((p_Result_377_fu_406_p3[0:0] == 1'b1) ? select_ln934_32_fu_466_p3 : Range1_all_zeros_32_fu_452_p2);

assign deleted_zeros_33_fu_602_p3 = ((p_Result_379_fu_534_p3[0:0] == 1'b1) ? select_ln934_33_fu_594_p3 : Range1_all_zeros_33_fu_580_p2);

assign deleted_zeros_34_fu_730_p3 = ((p_Result_381_fu_662_p3[0:0] == 1'b1) ? select_ln934_34_fu_722_p3 : Range1_all_zeros_34_fu_708_p2);

assign deleted_zeros_35_fu_858_p3 = ((p_Result_383_fu_790_p3[0:0] == 1'b1) ? select_ln934_35_fu_850_p3 : Range1_all_zeros_35_fu_836_p2);

assign deleted_zeros_36_fu_986_p3 = ((p_Result_385_fu_918_p3[0:0] == 1'b1) ? select_ln934_36_fu_978_p3 : Range1_all_zeros_36_fu_964_p2);

assign deleted_zeros_37_fu_1114_p3 = ((p_Result_387_fu_1046_p3[0:0] == 1'b1) ? select_ln934_37_fu_1106_p3 : Range1_all_zeros_37_fu_1092_p2);

assign deleted_zeros_38_fu_1242_p3 = ((p_Result_389_fu_1174_p3[0:0] == 1'b1) ? select_ln934_38_fu_1234_p3 : Range1_all_zeros_38_fu_1220_p2);

assign deleted_zeros_fu_218_p3 = ((p_Result_373_fu_150_p3[0:0] == 1'b1) ? select_ln934_fu_210_p3 : Range1_all_zeros_fu_196_p2);

assign icmp_ln1695_31_fu_242_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_32_fu_370_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_33_fu_498_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_34_fu_626_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_35_fu_754_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_36_fu_882_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_37_fu_1010_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_38_fu_1138_p2 = (($signed(p_read8) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1695_fu_114_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign or_ln420_31_fu_286_p2 = (r_31_fu_274_p1 | p_Result_350_fu_258_p3);

assign or_ln420_32_fu_414_p2 = (r_32_fu_402_p1 | p_Result_353_fu_386_p3);

assign or_ln420_33_fu_542_p2 = (r_33_fu_530_p1 | p_Result_356_fu_514_p3);

assign or_ln420_34_fu_670_p2 = (r_34_fu_658_p1 | p_Result_359_fu_642_p3);

assign or_ln420_35_fu_798_p2 = (r_35_fu_786_p1 | p_Result_362_fu_770_p3);

assign or_ln420_36_fu_926_p2 = (r_36_fu_914_p1 | p_Result_365_fu_898_p3);

assign or_ln420_37_fu_1054_p2 = (r_37_fu_1042_p1 | p_Result_368_fu_1026_p3);

assign or_ln420_38_fu_1182_p2 = (r_38_fu_1170_p1 | p_Result_371_fu_1154_p3);

assign or_ln420_fu_158_p2 = (r_fu_146_p1 | p_Result_s_fu_130_p3);

assign p_Result_350_fu_258_p3 = p_read1[32'd2];

assign p_Result_353_fu_386_p3 = p_read2[32'd2];

assign p_Result_356_fu_514_p3 = p_read3[32'd2];

assign p_Result_359_fu_642_p3 = p_read4[32'd2];

assign p_Result_362_fu_770_p3 = p_read5[32'd2];

assign p_Result_365_fu_898_p3 = p_read6[32'd2];

assign p_Result_368_fu_1026_p3 = p_read7[32'd2];

assign p_Result_371_fu_1154_p3 = p_read8[32'd2];

assign p_Result_372_fu_138_p3 = p_read[32'd1];

assign p_Result_373_fu_150_p3 = p_read[32'd9];

assign p_Result_374_fu_266_p3 = p_read1[32'd1];

assign p_Result_375_fu_278_p3 = p_read1[32'd9];

assign p_Result_376_fu_394_p3 = p_read2[32'd1];

assign p_Result_377_fu_406_p3 = p_read2[32'd9];

assign p_Result_378_fu_522_p3 = p_read3[32'd1];

assign p_Result_379_fu_534_p3 = p_read3[32'd9];

assign p_Result_380_fu_650_p3 = p_read4[32'd1];

assign p_Result_381_fu_662_p3 = p_read4[32'd9];

assign p_Result_382_fu_778_p3 = p_read5[32'd1];

assign p_Result_383_fu_790_p3 = p_read5[32'd9];

assign p_Result_384_fu_906_p3 = p_read6[32'd1];

assign p_Result_385_fu_918_p3 = p_read6[32'd9];

assign p_Result_386_fu_1034_p3 = p_read7[32'd1];

assign p_Result_387_fu_1046_p3 = p_read7[32'd9];

assign p_Result_388_fu_1162_p3 = p_read8[32'd1];

assign p_Result_389_fu_1174_p3 = p_read8[32'd9];

assign p_Result_s_fu_130_p3 = p_read[32'd2];

assign p_Val2_101_fu_174_p2 = (p_Val2_s_fu_120_p4 + zext_ln423_fu_170_p1);

assign p_Val2_102_fu_248_p4 = {{p_read1[9:2]}};

assign p_Val2_103_fu_302_p2 = (p_Val2_102_fu_248_p4 + zext_ln423_31_fu_298_p1);

assign p_Val2_104_fu_376_p4 = {{p_read2[9:2]}};

assign p_Val2_105_fu_430_p2 = (p_Val2_104_fu_376_p4 + zext_ln423_32_fu_426_p1);

assign p_Val2_106_fu_504_p4 = {{p_read3[9:2]}};

assign p_Val2_107_fu_558_p2 = (p_Val2_106_fu_504_p4 + zext_ln423_33_fu_554_p1);

assign p_Val2_108_fu_632_p4 = {{p_read4[9:2]}};

assign p_Val2_109_fu_686_p2 = (p_Val2_108_fu_632_p4 + zext_ln423_34_fu_682_p1);

assign p_Val2_110_fu_760_p4 = {{p_read5[9:2]}};

assign p_Val2_111_fu_814_p2 = (p_Val2_110_fu_760_p4 + zext_ln423_35_fu_810_p1);

assign p_Val2_112_fu_888_p4 = {{p_read6[9:2]}};

assign p_Val2_113_fu_942_p2 = (p_Val2_112_fu_888_p4 + zext_ln423_36_fu_938_p1);

assign p_Val2_114_fu_1016_p4 = {{p_read7[9:2]}};

assign p_Val2_115_fu_1070_p2 = (p_Val2_114_fu_1016_p4 + zext_ln423_37_fu_1066_p1);

assign p_Val2_116_fu_1144_p4 = {{p_read8[9:2]}};

assign p_Val2_117_fu_1198_p2 = (p_Val2_116_fu_1144_p4 + zext_ln423_38_fu_1194_p1);

assign p_Val2_s_fu_120_p4 = {{p_read[9:2]}};

assign r_31_fu_274_p1 = p_read1[0:0];

assign r_32_fu_402_p1 = p_read2[0:0];

assign r_33_fu_530_p1 = p_read3[0:0];

assign r_34_fu_658_p1 = p_read4[0:0];

assign r_35_fu_786_p1 = p_read5[0:0];

assign r_36_fu_914_p1 = p_read6[0:0];

assign r_37_fu_1042_p1 = p_read7[0:0];

assign r_38_fu_1170_p1 = p_read8[0:0];

assign r_fu_146_p1 = p_read[0:0];

assign select_ln1695_31_fu_362_p3 = ((icmp_ln1695_31_fu_242_p2[0:0] == 1'b1) ? select_ln348_31_fu_354_p3 : 8'd0);

assign select_ln1695_32_fu_490_p3 = ((icmp_ln1695_32_fu_370_p2[0:0] == 1'b1) ? select_ln348_32_fu_482_p3 : 8'd0);

assign select_ln1695_33_fu_618_p3 = ((icmp_ln1695_33_fu_498_p2[0:0] == 1'b1) ? select_ln348_33_fu_610_p3 : 8'd0);

assign select_ln1695_34_fu_746_p3 = ((icmp_ln1695_34_fu_626_p2[0:0] == 1'b1) ? select_ln348_34_fu_738_p3 : 8'd0);

assign select_ln1695_35_fu_874_p3 = ((icmp_ln1695_35_fu_754_p2[0:0] == 1'b1) ? select_ln348_35_fu_866_p3 : 8'd0);

assign select_ln1695_36_fu_1002_p3 = ((icmp_ln1695_36_fu_882_p2[0:0] == 1'b1) ? select_ln348_36_fu_994_p3 : 8'd0);

assign select_ln1695_37_fu_1130_p3 = ((icmp_ln1695_37_fu_1010_p2[0:0] == 1'b1) ? select_ln348_37_fu_1122_p3 : 8'd0);

assign select_ln1695_38_fu_1258_p3 = ((icmp_ln1695_38_fu_1138_p2[0:0] == 1'b1) ? select_ln348_38_fu_1250_p3 : 8'd0);

assign select_ln1695_fu_234_p3 = ((icmp_ln1695_fu_114_p2[0:0] == 1'b1) ? select_ln348_fu_226_p3 : 8'd0);

assign select_ln348_31_fu_354_p3 = ((deleted_zeros_31_fu_346_p3[0:0] == 1'b1) ? p_Val2_103_fu_302_p2 : 8'd255);

assign select_ln348_32_fu_482_p3 = ((deleted_zeros_32_fu_474_p3[0:0] == 1'b1) ? p_Val2_105_fu_430_p2 : 8'd255);

assign select_ln348_33_fu_610_p3 = ((deleted_zeros_33_fu_602_p3[0:0] == 1'b1) ? p_Val2_107_fu_558_p2 : 8'd255);

assign select_ln348_34_fu_738_p3 = ((deleted_zeros_34_fu_730_p3[0:0] == 1'b1) ? p_Val2_109_fu_686_p2 : 8'd255);

assign select_ln348_35_fu_866_p3 = ((deleted_zeros_35_fu_858_p3[0:0] == 1'b1) ? p_Val2_111_fu_814_p2 : 8'd255);

assign select_ln348_36_fu_994_p3 = ((deleted_zeros_36_fu_986_p3[0:0] == 1'b1) ? p_Val2_113_fu_942_p2 : 8'd255);

assign select_ln348_37_fu_1122_p3 = ((deleted_zeros_37_fu_1114_p3[0:0] == 1'b1) ? p_Val2_115_fu_1070_p2 : 8'd255);

assign select_ln348_38_fu_1250_p3 = ((deleted_zeros_38_fu_1242_p3[0:0] == 1'b1) ? p_Val2_117_fu_1198_p2 : 8'd255);

assign select_ln348_fu_226_p3 = ((deleted_zeros_fu_218_p3[0:0] == 1'b1) ? p_Val2_101_fu_174_p2 : 8'd255);

assign select_ln934_31_fu_338_p3 = ((tmp_243_fu_330_p3[0:0] == 1'b1) ? Range1_all_zeros_31_fu_324_p2 : Range1_all_ones_31_fu_318_p2);

assign select_ln934_32_fu_466_p3 = ((tmp_247_fu_458_p3[0:0] == 1'b1) ? Range1_all_zeros_32_fu_452_p2 : Range1_all_ones_32_fu_446_p2);

assign select_ln934_33_fu_594_p3 = ((tmp_251_fu_586_p3[0:0] == 1'b1) ? Range1_all_zeros_33_fu_580_p2 : Range1_all_ones_33_fu_574_p2);

assign select_ln934_34_fu_722_p3 = ((tmp_255_fu_714_p3[0:0] == 1'b1) ? Range1_all_zeros_34_fu_708_p2 : Range1_all_ones_34_fu_702_p2);

assign select_ln934_35_fu_850_p3 = ((tmp_259_fu_842_p3[0:0] == 1'b1) ? Range1_all_zeros_35_fu_836_p2 : Range1_all_ones_35_fu_830_p2);

assign select_ln934_36_fu_978_p3 = ((tmp_263_fu_970_p3[0:0] == 1'b1) ? Range1_all_zeros_36_fu_964_p2 : Range1_all_ones_36_fu_958_p2);

assign select_ln934_37_fu_1106_p3 = ((tmp_267_fu_1098_p3[0:0] == 1'b1) ? Range1_all_zeros_37_fu_1092_p2 : Range1_all_ones_37_fu_1086_p2);

assign select_ln934_38_fu_1234_p3 = ((tmp_271_fu_1226_p3[0:0] == 1'b1) ? Range1_all_zeros_38_fu_1220_p2 : Range1_all_ones_38_fu_1214_p2);

assign select_ln934_fu_210_p3 = ((tmp_fu_202_p3[0:0] == 1'b1) ? Range1_all_zeros_fu_196_p2 : Range1_all_ones_fu_190_p2);

assign tmp21_fu_180_p4 = {{p_read[15:10]}};

assign tmp_243_fu_330_p3 = p_Val2_103_fu_302_p2[32'd7];

assign tmp_247_fu_458_p3 = p_Val2_105_fu_430_p2[32'd7];

assign tmp_251_fu_586_p3 = p_Val2_107_fu_558_p2[32'd7];

assign tmp_255_fu_714_p3 = p_Val2_109_fu_686_p2[32'd7];

assign tmp_259_fu_842_p3 = p_Val2_111_fu_814_p2[32'd7];

assign tmp_263_fu_970_p3 = p_Val2_113_fu_942_p2[32'd7];

assign tmp_267_fu_1098_p3 = p_Val2_115_fu_1070_p2[32'd7];

assign tmp_271_fu_1226_p3 = p_Val2_117_fu_1198_p2[32'd7];

assign tmp_28_fu_308_p4 = {{p_read1[15:10]}};

assign tmp_67_fu_564_p4 = {{p_read3[15:10]}};

assign tmp_68_fu_692_p4 = {{p_read4[15:10]}};

assign tmp_69_fu_820_p4 = {{p_read5[15:10]}};

assign tmp_70_fu_948_p4 = {{p_read6[15:10]}};

assign tmp_71_fu_1076_p4 = {{p_read7[15:10]}};

assign tmp_72_fu_1204_p4 = {{p_read8[15:10]}};

assign tmp_fu_202_p3 = p_Val2_101_fu_174_p2[32'd7];

assign tmp_s_fu_436_p4 = {{p_read2[15:10]}};

assign zext_ln423_31_fu_298_p1 = and_ln420_31_fu_292_p2;

assign zext_ln423_32_fu_426_p1 = and_ln420_32_fu_420_p2;

assign zext_ln423_33_fu_554_p1 = and_ln420_33_fu_548_p2;

assign zext_ln423_34_fu_682_p1 = and_ln420_34_fu_676_p2;

assign zext_ln423_35_fu_810_p1 = and_ln420_35_fu_804_p2;

assign zext_ln423_36_fu_938_p1 = and_ln420_36_fu_932_p2;

assign zext_ln423_37_fu_1066_p1 = and_ln420_37_fu_1060_p2;

assign zext_ln423_38_fu_1194_p1 = and_ln420_38_fu_1188_p2;

assign zext_ln423_fu_170_p1 = and_ln420_fu_164_p2;

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config4_s
